name: amplifycrashtest
description: A new Flutter project.
publish_to: 'none'

version: 1.8.6+39

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  amplify_auth_cognito: 1.7.2
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.2
  flutter_jailbreak_detection: 1.10.0
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  get: 4.6.5
  get_it: 7.4.0
  hive_flutter: 1.1.0
  http: 0.13.5
  intl: 0.18.1
  responsive_framework: 0.2.0

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.4.8
  csslib: 0.17.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  lint: ^2.0.1
  mockito: ^5.4.2
  remove_from_coverage: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
